"""
Django settings for shiv project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l_sp3p9%99$1wntttz=5e#g_sbsyf-0-c-l9lc62e=#hv^%vdl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shiv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shiv.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'assets/'

STATICFILES_DIRS = ["assets"]
# STATIC_ROOT = os.path.join(BASE_DIR, "assets")
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ENVIRONMENTS = {
    "INT01-US": {
        "url": "https://na-uat.api.mcd.com",
        "clientId": "508747ceaec649079c0022b6c8d8052e",
        "clientSecret": "A7a0eAc903BF479A927e1A1061c89356",
        "authCode": "NTA4NzQ3Y2VhZWM2NDkwNzljMDAyMmI2YzhkODA1MmU6QTdhMGVBYzkwM0JGNDc5QTkyN2UxQTEwNjFjODkzNTY="
    },
    "US-STG01": {
        "url": "https://mcd-na-stg.digitalecp.mcd.com",
        "clientId": "8EA5RYUgznbyuRYasZt6EzBg9Rvr26wZ",
        "clientSecret": "k6VBtyvRxyVrG3MHUwhcnc6PX77JPtpP",
        "authCode": "OEVBNVJZVWd6bmJ5dVJZYXNadDZFekJnOVJ2cjI2d1o6azZWQnR5dlJ4eVZyRzNNSFV3aGNuYzZQWDc3SlB0cFA="
    },
    "US-STAG01": {
        "url": "https://mcd-us-stg.digitalecp.mcd.com",
        "clientId": "87MGQuRSYNFgdwnWTVjkzFGkDdrFj9X4",
        "clientSecret": "Dh34YRsnqW6wuwJKKDxdnTSF6hXKpWuD",
        "authCode": "ODdNR1F1UlNZTkZnZHduV1RWamt6RkdrRGRyRmo5WDQ6RGgzNFlSc25xVzZ3dXdKS0tEeGRuVFNGNmhYS3BXdUQ="
    },
    "CA-STG01": {
        "url": "https://mcd-na-stg.digitalecp.mcd.com",
        "clientId": "3taq7EW85wZDYWavSRYAyDJFGxBeSwkP",
        "clientSecret": "tzUsv25TALd3rKAgF4UyGnqFDE5B4caR",
        "authCode": "M3RhcTdFVzg1d1pEWVdhdlNSWUF5REpGR3hCZVN3a1A6dHpVc3YyNVRBTGQzcktBZ0Y0VXlHbnFGREU1QjRjYVI="
    },
    "CA-MTE01": {
        "url": "https://mcd-na-mte.digitalecp.mcd.com",
        "clientId": "RjGMyVYBGBnYMJKs3AVVgUVhvk5DHNr5",
        "clientSecret": "msJJ8SQgCfWuBknWge2FECeJnW4JJHBp",
        "authCode": "UmpHTXlWWUJHQm5ZTUpLczNBVlZnVVZodms1REhOcjU6bXNKSjhTUWdDZld1QmtuV2dlMkZFQ2VKblc0SkpIQnA="
    },
    "DE-STG01": {
        "url": "https://mcd-eu-stg.digitalecp.mcd.com",
        "clientId": "8hh4PhgH2CDD778mEgrCJvgSqw8t9wrS",
        "clientSecret": "MHD7aJfZmpnjdvAFSwjnK7U4jVqntpd5",
        "authCode": "OGhoNFBoZ0gyQ0RENzc4bUVnckNKdmdTcXc4dDl3clM6TUhEN2FKZlptcG5qZHZBRlN3am5LN1U0alZxbnRwZDU"
    },
    "DE-MTE01": {
        "url": "https://eu-mte.api.mcd.com",
        "clientId": "89dxDAL29mGtCA4p8ZWNqy3x9UKpHvat",
        "clientSecret": "3dFZTfdXZgt48hJTZj7jJXV3cvuAP9HF",
        "authCode": "ODlkeERBTDI5bUd0Q0E0cDhaV05xeTN4OVVLcEh2YXQ6M2RGWlRmZFhaZ3Q0OGhKVFpqN2pKWFYzY3Z1QVA5SEY"
    },
    "UK-STG01": {
        "url": "https://mcd-eu-stg.digitalecp.mcd.com",
        "clientId": "2JgRptHSXwLHbezDNHNrBN9PzQgyFwjU",
        "clientSecret": "Nkm5tcWFghdtBtEgaULSW4wKaUUDTMsW",
        "authCode": "MkpnUnB0SFNYd0xIYmV6RE5ITnJCTjlQelFneUZ3alU6TmttNXRjV0ZnaGR0QnRFZ2FVTFNXNHdLYVVVRFRNc1c"
    },
    "UK-MTE01": {
        "url": "https://mcd-eu-mte.digitalecp.mcd.com",
        "clientId": "6089npvFFuA6dsQn5YPgKmlhtzT8MskJ",
        "clientSecret": "1SWyXNfXzg2eKj8bDzwNr8wfuyfo9N09",
        "authCode": "NjA4OW5wdkZGdUE2ZHNRbjVZUGdLbWxodHpUOE1za0o6MVNXeVhOZlh6ZzJlS2o4YkR6d05yOHdmdXlmbzlOMDk="
    },
    "AU-MTE01": {
        "url": "https://ap-mte.api.mcd.com",
        "clientId": "fb5dad675b18449ebd299780f3938fad",
        "clientSecret": "Dh34YRsnqW6wuwJKKDxdnTSF6hXKpWuD",
        "authCode": "ZmI1ZGFkNjc1YjE4NDQ5ZWJkMjk5NzgwZjM5MzhmYWQ6RDhiYzM4Y0U2MWJBNDQwODhEMzlCNUQ3OTFkNUZjNTE="
    },
    "AU-STG01": {
        "url": "https://mcd-ap-stg.digitalecp.mcd.com",
        "clientId": "7N3bkRavRsH2YzdQdedEjWdSv9k3UvNE",
        "clientSecret": "zrPNraCb5RrrPKWKYk9N5wGvaFj33sUc",
        "authCode": "N04zYmtSYXZSc0gyWXpkUWRlZEVqV2RTdjlrM1V2TkU6enJQTnJhQ2I1UnJyUEtXS1lrOU41d0d2YUZqMzNzVWM="
    },
}
