# Generated by Django 4.0.5 on 2022-06-11 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryWorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryId', models.CharField(default='', max_length=30)),
                ('checkingCode', models.CharField(default='', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('cancelled', 'Cancelled'), ('out_for_pickup', 'Out for pickup'), ('approaching_store', 'Approaching store'), ('out_for_delivery', 'Out for delivery'), ('approaching_customer_location', 'Approaching customer location'), ('delivered', 'Delivered')], default='awaiting', max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancellingParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cancelling_party', to='app.party')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_environment', to='app.environment')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_market', to='app.market')),
                ('partyAtFault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_party_at_fault', to='app.party')),
            ],
        ),
    ]
