# Generated by Django 4.0.5 on 2022-06-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_deliveryworkflow_cancellingparty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryWorkFlow',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
